version: '3.1'

services:
  php:
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    command: bash -c "composer install --ignore-platform-reqs && /usr/sbin/apache2ctl -D FOREGROUND"